### PR TITLE
translate all markdown in folder and more

### PR DESCRIPTION
**Pull request by ryanhex53**
use axios instead of fetch;
translate all markdown in folder;
translate in sequence mode by default;
option --fast turn on parallel mode;
update build script;

### CODE REVIEW

**Comment by smikitky** [comment]
Thanks for the PR, but I cannot merge this as-is. This PR does too many things at once, and unfortunately I cannot agree with everything in the PR.

- What is the reason for using Axios? I like node-fetch for a reason.
- I didn't know there is a [3 request/min limit](https://platform.openai.com/docs/guides/rate-limits/overview) for free trial users, so I agree that something can be done. However, even a paid account has a rate limit, and you can easily hit the limit when translating many files in parallel. So I think some throttling function that is smarter than `--fast` needs to be implemented (e.g. `--rpm=3` that works whether you're translating one file or many files). I'm thinking of introducing a "gate" function that limits the frequency of `callAPi()`.
- I know it's nice to install this tool globally via NPM, but I'd rather do this setup myself when I believe it's ready.

**Comment by ryanhex53** [comment]
- The reason why I use `axios` is that `node-fetch` does not pick up the system proxy setting after setting the environment variable `HTTPS_PROXY` in Windows (I am not sure about UNIX). This is important for me because I cannot access the OpenAI API without a proxy. Additionally, the npm package `openai` also uses `axios` as its dependency. 
- I think you don't have to, in this version, files translating is in sequence mode (One by one). And the `--fast` option is the same version as yours.
- You do not have to install globally from npm; It is an optional choice for users. If someone clones the code, they can run `npm build && npm link` once. Then, the command `markdown-gpt-translator` can be used anywhere, not just under the project directory. This is very convenient when I need to translate files from anywhere on my computer. Using `npx <pkg> <file> <params>` every time is not a good practice for daily use.

IMO, you can absolutely merge the PR and then modify it again. It doesn't change a lot.

**Comment by ryanhex53** [comment]
- The reason why I use `axios` is that `node-fetch` does not pick up the system proxy setting after setting the environment variable `HTTPS_PROXY` in Windows (I am not sure about UNIX). This is important for me because I cannot access the OpenAI API without a proxy. Additionally, the npm package `openai` also uses `axios` as its dependency. 
- I think you don't have to, in this version, files translating are in sequence mode (One by one).
- You do not have to install globally from npm; It is an optional choice for users. If someone clones the code, they can run `npm build && npm link` once. Then, the command `markdown-gpt-translator` can be used anywhere, not just under the project directory. This is very convenient when I need to translate files from anywhere on my computer. Using `npx <pkg> <file> <params>` every time is not a good practice for daily use.

IMO, you can absolutely merge the PR and then modify it again. It doesn't change a lot.

**Comment by smikitky** [comment]
This PR tries to solve 4 unrelated problems. Here are my comments for each of them. 

- **HTTP Proxy** *(needs to be implemented differently)*: Looks like node-fetch can use a proxy with [this approach](https://www.scrapingbee.com/blog/proxy-node-fetch/) (a [thin rapper here](https://www.npmjs.com/package/node-fetch-with-proxy)). Rather than migrating to Axios, I prefer trying this approach.
- **API Rate Limit** *(needs to be implemented differently)*: I have instructed everyone to register their own credit card to OpenAI, and pay-as-you-go users don't need to process fragments sequentially. Therefore, the `--fast` behavior must be the default, as it is now. Perhaps we can introduce a new option such as `--api-interval=20000` to limit the rate of API calls.
- **Multifile Support** *(reject)*: If you want to translate multiple files but don't need parallel translation across many files, you can just use `xargs` in combination with `find` (Git Bash for Windows has these tools). Even if we need to translate many files simultaneously taking the rate limit into consideration, I prefer `glob`, like most other libraries do. Those approaches are much more flexible than the current "dot" (`.`) approach which only works with CWD.
- **Global Installation** *(accept)*: As you said, `npm build && npm link` seems to be a nice addition.

Unfortunately, it is impossible to merge this PR altogether now, since I cannot immediately agree on everything. However, the Proxy and Rate Limit problems are issues I was not aware of, and I think they should be addressed. I filed the issues #3 and #4. I think I can add these myself in a week or so.

**Comment by smikitky** [comment]
If you don't like `xargs`, you can also write a Bash script like this (should work on Git Bash for Windows, too):

```
#!/bin/bash

shopt -s globstar
for file in /src/learn/**/*.md; do
  npx ts-node-esm index.ts -m 4 "$file"
done
```

**Comment by smikitky** [comment]
I added the two options in `.env`. You can now set something like this:

```env
# Do not call API more than once per 20 sec
API_CALL_INTERVAL=20

# HTTPS Proxy
HTTPS_PROXY="http://1.2.3.4:8080"
```

**Pull request closed without merging**
